### ISSUE TITLE
Lof In fails with MS 2017 SQL Python Script

### ISSUE THREAD

**Issue by harrynicol** [webdjoe/pyvesync_v2#17]
Can log into VeSync with Visual Studio and Jupiter Notebooks but running the same script on MS 2017 SQL Server VeSync log in fails.  Any ideas?

**Comment by webdjoe** [comment]
What error are you getting?  There should be a log entry that lets you narrow it down to an incorrect password or a failed request

**Comment by harrynicol** [comment]
Hi Joe,

Impressed by the Saturday night reply, thanks.

Simple Log In Script

EXEC sp_execute_external_script
@language = N'Python',
@script = N'
from pyvesync import VeSync
manager = VeSync("harrynicol@nc.rr.com", "xxxxxxxxxx")
manager.login()
'
Error returned

STDERR message(s) from external script:
2020-01-12 06:14:42,436 - ERROR - HTTPSConnectionPool(host='smartapi.vesync.com', port=443): Max retries exceeded with url: /cloud/v1/user/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000124C4B3FBE0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions',))
2020-01-12 06:14:42,440 - ERROR - Error logging in with username and password
Other

Pyvesync-v2 is the same
SQL Log is as below
01/12/2020 06:21:14,spid56,Unknown,SQL Server received abort message and abort execution for major error : 18 and minor error : 42

Many thanks

Harry Nicol
8768 Wildwood Links
Raleigh NC 27613
919-757-711

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by webdjoe** [comment]
That usually means a firewall is blocking the port.  On my computer all outgoing connections are blocked that aren't allowed by a rule.  I get that error when running in a new python virtual environment that I haven't allowed through.  Check your firewall settings and make sure that python executable running the script is allowed through

**Comment by harrynicol** [comment]
Disabled the firewall on the server hosting the SQL instance that runs the MI python scripts. That removed the error. As u would expect, as you have, few open ports as necessary. Now the problem is finding the port to open. Will work on this tomorrow and will let u know. Still but if a puzzle. On my workstation that also runs MS SQL server python scripts it fails but Visua Studio and Jupiter notebooks run with out error


Harry Nicol
8768 Wildwood Links
Raleigh NC 27613
919-757-1711
harrynicol@thescottishedge.com


________________________________

**Comment by webdjoe** [comment]
I'm guessing the server is running windows.  Just allow that python executable installed with sql server outgoing on port 443

**Comment by harrynicol** [comment]
Resolved. Windows firewal log was showing Deny for 443 when running python from sql instance and Allow for 443 from Visual Studio. That did not make any sense as python was enabled thro the firewall. Had to be something else. In the firewall R access for the SQL instance was blocked but no mention of python. So worth a try so enabled access and bingo it also worked for python.

Thanks for the input and thanks for doing the API. Now I can complete my MI project

Harry Nicol
8768 Wildwood Links
Raleigh NC 27613
919-757-1711
harrynicol@thescottishedge.com


________________________________
