### ISSUE TITLE
Adding support for airpurifiers

### ISSUE THREAD

**Issue by rzolau** [webdjoe/pyvesync_v2#4]
VeSync currently supports air purifiers. As far as I can tell by tracing their app, the API is very similar to the one used for switches (in fact, using `call_api` from pyvesync I was able to talk to my purifier with some small updates to json payload). If that is something of interest, I may contribute my code, although the project would then evolve beyond switches :-)

**Comment by webdjoe** [comment]
I'm currently collaborating with the original creator @markperdue so any future updates will be to https://github.com/markperdue/pyvesync.  If you want to send me your packet captures from the device list (first list of devices you see when you login), device details (when you press on the device in the list) and the calls to turn on/off or any other functions I will incorporate them into the next update

**Comment by rzolau** [comment]
OK, I should have some free cycles over the weekend, will compile the list.

**Comment by rzolau** [comment]
I sent you session trace with requested details via email.
